### ISSUE TITLE
期待

### ISSUE THREAD

**Issue by AlchemyDing** [plasticene/plasticene-boot-starter-parent#2]
加油，期待基于lettuce的redis starter和Jedis原生而不是spring-data的jedis starter

**Comment by ShepherdZFJ** [comment]
> 加油，期待基于lettuce的redis starter和Jedis原生而不是spring-data的jedis starter

一起加油💪🏻，一起学习，后面这个期待问题没看懂.....，有什么好的idea，方便的话可以在我个人主页加我微信号详聊畅谈
